Update ckdeps english

diff --git a/ckdeps b/ckdeps
--- a/ckdeps
+++ b/ckdeps
@@ -1,16 +1,16 @@
 #!/bin/bash
 #
-# CKDeps - Versão 6.2.2 - Analisa Dependências de Aplicativos Binários Instalado no Slackware
+# CKDeps - Version 6.2.2 - Analyzes Dependencies of Binary Applications Installed on Slackware
 #
 # Criação do Projeto: 04/04/2021
-# Última Atualização: 25/06/2023
+# Last update: 25/06/2023
 #
 # By Mauricio Ferrari. Santa Catarina, Brasil.
-#
+# Transalte into English by Locutus
 ###############################################################################################
 
 
-# Definição de Variáveis
+# Definition of Variables
 
 r='\e[31m'
 g='\e[32m'
@@ -25,23 +25,23 @@ apkg='FALSE'
 cpkg='FALSE'
 
 
-#  Exibição de Informação
+#  Information Display
 
 function info_view
 {
 
 printf "\n${b}CKDeps v$(grep -Eo "[0-9].[0-9]" <(head -3 $0))
-Pesquisa por Pacotes Instalados e Procura por Dependências Faltantes em Binários.\n
-${g}Sintaxe: $y${0##*/} $r<Parâmetros> \e[33margumentos\n
-${g}Parâmetros:
-\t$r-b <binário> $b:$y Pesquisa por Dependências em Executáveis Binários.
-\t$r-s <pacotes> $b:$y Pesquisa Básica de Pacotes Instalados no Sistema.
-\t$r-S <pacotes> $b:$y Pesquisa Avançada de Pacotes Instalados no Sistema.
-\t$r-c <arquivo> $b:$y Pesquisa por um Arquivo no Conteúdo dos Pacotes Instalados.\n
-${g}Parâmetros Extras:
-\t${r}i $b:$y Ignora Diferenças Entre Maiúsculas/Minúsculas.
-\t    Pode ser usado com os Parâmetros$r s$y,${r}S$y e$r c$y.\n
-${g}Exemplos de Uso:
+Searching for Installed Packages and Searching for Missing Dependencies in Binaries.\n
+${g}Syntax: $y${0##*/} $r<Parameters> \e[33margumentos\n
+${g}Parameters:
+\t$r-b <binary> $b:$y Searching for Dependencies in Binary Executables.
+\t$r-s <packages> $b:$y Basic Search of Installed Packages on the System.
+\t$r-S <packages> $b:$y Advanced Search of Installed Packages on the System.
+\t$r-c <archive> $b:$y Searching for a File in the Contents of Installed Packages.\n
+${g}Extra Parameters:
+\t${r}i $b:$y Ignore Uppercase/Lowercase Differences.
+\t    Can be used with Parameters$r s$y,${r}S$y e$r c$y.\n
+${g}Usage Examples:
 \t$y${0##*/} $r-b$c /usr/bin/megasync
 \t$y${0##*/} $r-s$c gcc libtorrent
 \t$y${0##*/} $r-Si$c qmplay2 wxgtk3
@@ -51,12 +51,12 @@ exit 0
 }
 
 
-# Entrada de Parâmetros
+# Parameter Input
 
 [ -t 0 ] && {
     [ ! "$1" ] && info_view || true
 } || {
-    set - $* $(cat -) # Suporte a Redirecionamento
+    set - $* $(cat -) # Redirect Support
 }
 
 arg=${*#$1}
@@ -74,39 +74,38 @@ while getopts bsSci option 2>&-; do
 done
 
 
-#  Verificar Dependências Faltantes
-
+# Check Missing Dependencies
 [ "$clib" == "TRUE" ] && {
     [ ! $(($#-1)) -eq 1 ] && {
-        printf "\n${r}Muitos Parâmetros!$t\n\n" >&2
+        printf "\n${r}Too Many Parameters!$t\n\n" >&2
         exit 1
     }
 
     [ ! -e $arg ] && {
-        printf "\n${r}Arquivo Inexistente!$t\n\n" >&2
+        printf "\n${r}Non-existent file!$t\n\n" >&2
         exit 1
     }
 
     ckbin=$(ldd $arg 2>&-)
 
     [ -z "$ckbin" ] && {
-        printf "\n${r}Não é um Executável Binário Válido!$t\n\n" >&2
+        printf "\n${r}Not a Valid Binary Executable!$t\n\n" >&2
         exit 1
     }
 
     cklib=$(awk -F= '{print $1}' <(grep '=> not found' <<< $ckbin))
-    printf "\n${y}Dependências Faltantes: $b($(wc -w <<< $cklib))$r\n$cklib$t\n\n"
+    printf "\n${y}Missing Dependencies: $b($(wc -w <<< $cklib))$r\n$cklib$t\n\n"
     exit 0
 }
 
 
-#  Operações para Pesquisas
+#  Research Operations
 
 cd /var/log/packages
 lst=$(printf "%s\n" *)
 
 
-#  Pesquisa de Pacotes
+#  Package Search
 
 [ "$spkg" == "TRUE" ] && {
     for pkg in $arg
@@ -114,26 +113,25 @@ lst=$(printf "%s\n" *)
         found=$(echo -e "$found\n$(grep $parm "$pkg" <<< $lst)")
     }
     found=$(sort -u <<< $found)
-    printf "\n${y}Pacotes Encontrados: $b($(wc -w <<< $found))$c$(sed "s/^/	/" <<< $found)$t\n\n"
+    printf "\n${y}Packages Found: $b($(wc -w <<< $found))$c$(sed "s/^/	/" <<< $found)$t\n\n"
     exit 0
 }
 
 
-#  Pesquisa Avançada de Pacotes
-
+#  Advanced Package Search
 [ "$apkg" == "TRUE" ] && {
     for pkg in $arg
     {
         verify=$(grep $parm "^$pkg-[0-9]" <<< $lst)
         [ ! "$verify" ] && notfound=$(echo -e "$notfound\n\t$pkg") || found=$(echo -e "$found\n\t$verify")
     }
-    printf "\n${y}Pacotes Encontrados: $b($(wc -w <<< $found))$g$(sort <<< $found)$t\n"
-    printf "\n${y}Pacotes Não Encontrados: $b($(wc -w <<< $notfound))$r$(sort <<< $notfound)$t\n\n"
+    printf "\n${y}Packages Found: $b($(wc -w <<< $found))$g$(sort <<< $found)$t\n"
+    printf "\n${y}Packages Not Found: $b($(wc -w <<< $notfound))$r$(sort <<< $notfound)$t\n\n"
     exit 0
 }
 
 
-#  Pesquisa no Conteúdo do Pacote
+#  Package Content Search
 
 [ "$cpkg" == "TRUE" ] && {
     for pkg in $(sort <(fmt -1 <<< $arg))
